from __future__ import annotations

TASK_STATUS_TODO = "todo"
TASK_STATUS_IN_PROGRESS = "in_progress"
TASK_STATUS_DONE = "done"
TASK_STATUSES = {TASK_STATUS_TODO, TASK_STATUS_IN_PROGRESS, TASK_STATUS_DONE}

SORTABLE_FIELDS = {"due_date", "created_at", "title"}
DEFAULT_PAGE_SIZE = 10

NOTIFICATION_MAX_RETRIES = 3
NOTIFICATION_RETRY_COUNTDOWN = 5
